cmd/common/save.go, cmd/root.go, cmd/security/check_access_control.go, result/eks-checklist-access-control/access-entries.json, result/eks-checklist-access-control/aws-auth-configmap.yaml
클러스터 접근 제어(Access entries, aws-auth 컨피그맵) 체크 기능을 의도에 맞게 코드를 수정했습니다.
=> 의도에 맞는 코드 재작성 accessControl

cmd/root.go, cmd/security/pod_to_pod_policy.go
- Pod-to-Pod 접근 제어 체크 기능에 대해 의도에 맞게 코드를 수정했습니다.
=> refactor pod_to_pod_policy.go

cmd/root.go, cmd/security/multi_tenancy.go
=> complete multi_tenancy

.gitignore, cmd/root.go, cmd/security/image_static_analysis_check.go
=> 이미지 정적 분석 체크 기능 완성

cmd/root.go, cmd/scalability/graceful_shutdown_check.go
Application에 Graceful shutdown 적용 - Manual
=> Application에 Graceful shutdown 적용 - Manual

cmd/root.go, cmd/scalability/node_delete_protection_label.go
=> 중요 Pod에 노드 삭제 방지용 Label 부여 - Manual

cmd/root.go, cmd/stability/pod_QoS.go
=> 애플리케이션 중요도에 따른 QoS 적용 - Automatic/Manual

cmd/root.go, cmd/stability/pv_volume_affinity.go
PV 사용시 volume affinity 위반 사항 체크 - Manual
=> PV 사용시 volume affinity 위반 사항 체크 - Manual

cmd/network/subnet_ip_capacity.go
=> VPC 서브넷에 충분한 IP 대역대 확보 - Automatic/Manual

cmd/network/load_balancer_usage_property.go, cmd/root.go
사용 사례에 맞는 로드밸런서 사용(ALB or NLB) - Manual
=> 사용 사례에 맞는 로드밸런서 사용(ALB or NLB) - Manual

cmd/root.go, cmd/security/unauthorizedAccessAlarm.go
=> 비정상 접근에 대한 알림 설정 - Manual

cmd/root.go, cmd/scalability/nodeScalingPolicy.go
=> 노드 확장/축소 정책 적용 - Manual

cmd/root.go, cmd/stability/pod_distruption_budget.go
=> 중요 워크로드에 대한 PDB(Pod Distruption Budget) 적용 - Automatic/Manual

cmd/network/aws_loadbalancer_pod_ip.go, cmd/network/aws_loadbalancer_pod_ip_test.go, cmd/network/readiness_gate.go, cmd/network/readiness_gate_test.go, cmd/root.go
=> 로드밸런서 컨트롤러가 없을 경우 관련 기능 전부 FAIL 처리 되도록함

cmd/security/container_root.go, result.yaml
=> 루트 유저가 아닌 유저로 컨테이너 실행 예외처리 추가

cmd/common/filter.go, cmd/kubernetes.go, cmd/root.go
=> getkubeconfig에서 flag 라이브러리 삭제 및 로직 변경 & 잘못된 매개변수 받을 시 프로그램 종료

.gitignore, cmd/common/format.go, cmd/common/printer.go, cmd/root.go, go.mod, go.sum, templates/report.html
=> html 추출 기능 완성

cmd/kubernetes.go, cmd/root.go
=> context & 클러스터 선택 기능 추가

cmd/aws.go, cmd/eks.go, cmd/kubernetes.go, cmd/root.go
=> kubeconfig AWS_Profile 환경변수 참고 기능 추가

cmd/security/dataplanePrivate_test.go, testdata/dataplane_private.yaml
=> fixed error for dataplane_Private test code

go.mod, mkdocs.yml
=> mkdocs 구조 변경

cmd/kubernetes.go, cmd/root.go, docs/index.md, manifest/output-html-job.yaml, policy/minimum-policy.json
=> eks클러스터 이름 & 리전 동적 할당
